# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: encore.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'encore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65ncore.proto\x12\x06\x65ncore\"%\n\x11ListEventsRequest\x12\x10\n\x08\x62ookable\x18\x01 \x01(\x08\"0\n\x0fListEventsReply\x12\x1d\n\x06\x65vents\x18\x01 \x03(\x0b\x32\r.encore.Event\"#\n\x0fGetEventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\"6\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x12\n\nseats_left\x18\x03 \x01(\x05\"2\n\nSeatUpdate\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nseats_left\x18\x02 \x01(\x05\x32\xbb\x01\n\x06\x45ncore\x12@\n\nListEvents\x12\x19.encore.ListEventsRequest\x1a\x17.encore.ListEventsReply\x12\x32\n\x08GetEvent\x12\x17.encore.GetEventRequest\x1a\r.encore.Event\x12;\n\nWatchSeats\x12\x17.encore.GetEventRequest\x1a\x12.encore.SeatUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'encore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTEVENTSREQUEST']._serialized_start=24
  _globals['_LISTEVENTSREQUEST']._serialized_end=61
  _globals['_LISTEVENTSREPLY']._serialized_start=63
  _globals['_LISTEVENTSREPLY']._serialized_end=111
  _globals['_GETEVENTREQUEST']._serialized_start=113
  _globals['_GETEVENTREQUEST']._serialized_end=148
  _globals['_EVENT']._serialized_start=150
  _globals['_EVENT']._serialized_end=204
  _globals['_SEATUPDATE']._serialized_start=206
  _globals['_SEATUPDATE']._serialized_end=256
  _globals['_ENCORE']._serialized_start=259
  _globals['_ENCORE']._serialized_end=446
# @@protoc_insertion_point(module_scope)
