# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import encore_pb2 as encore__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in encore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EncoreStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListEvents = channel.unary_unary(
                '/encore.Encore/ListEvents',
                request_serializer=encore__pb2.ListEventsRequest.SerializeToString,
                response_deserializer=encore__pb2.ListEventsReply.FromString,
                _registered_method=True)
        self.GetEvent = channel.unary_unary(
                '/encore.Encore/GetEvent',
                request_serializer=encore__pb2.GetEventRequest.SerializeToString,
                response_deserializer=encore__pb2.Event.FromString,
                _registered_method=True)
        self.WatchSeats = channel.unary_stream(
                '/encore.Encore/WatchSeats',
                request_serializer=encore__pb2.GetEventRequest.SerializeToString,
                response_deserializer=encore__pb2.SeatUpdate.FromString,
                _registered_method=True)


class EncoreServicer:
    """Missing associated documentation comment in .proto file."""

    def ListEvents(self, request, context):
        """Safe: reading changes nothing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchSeats(self, request, context):
        """Server streaming: seatsLeft updates pushed as they change.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EncoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvents,
                    request_deserializer=encore__pb2.ListEventsRequest.FromString,
                    response_serializer=encore__pb2.ListEventsReply.SerializeToString,
            ),
            'GetEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvent,
                    request_deserializer=encore__pb2.GetEventRequest.FromString,
                    response_serializer=encore__pb2.Event.SerializeToString,
            ),
            'WatchSeats': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchSeats,
                    request_deserializer=encore__pb2.GetEventRequest.FromString,
                    response_serializer=encore__pb2.SeatUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'encore.Encore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('encore.Encore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Encore:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/encore.Encore/ListEvents',
            encore__pb2.ListEventsRequest.SerializeToString,
            encore__pb2.ListEventsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/encore.Encore/GetEvent',
            encore__pb2.GetEventRequest.SerializeToString,
            encore__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchSeats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/encore.Encore/WatchSeats',
            encore__pb2.GetEventRequest.SerializeToString,
            encore__pb2.SeatUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
